### ISSUE TITLE
Fragment bug

### ISSUE THREAD

**Issue by helfer** [apollostack/query-merging#1]
Issue on AC: https://github.com/apollostack/apollo-client/issues/598

PR on AC: https://github.com/apollostack/apollo-client/pull/599

@dahjelle: I'm factoring out query merging into a new package, so I will track the issues and PRs related to that in this repo from now on. In the meantime if you can, I would recommend using transport batching.

**Comment by chaffeqa** [comment]
Whats the status of this repo?  Is there anything we can do to test / help with this, or is it all set?

**Comment by stubailo** [comment]
Right now we're not planning on putting a lot of work into this type of query merging since it's quite hard to get it right, but we'll accept PRs to fix bugs.
