### ISSUE TITLE
Need this package?

### ISSUE THREAD

**Issue by helfer** [apollostack/query-merging#2]
This package currently still needs some work to be in shape for publishing on npm. If you need this package, please give this issue comment a 👍 and comment below how/why you need it.

**Comment by papandreou** [comment]
I'm just starting to use apollo-client and would like to explore merging of queries to limit the size of the query results as my app has a bunch of queries that fetch "overlapping" data.

Might be a Relay-ism on my part, though. I have no idea if it's actually worth the extra complexity. Still, it'd be nice to have this feature available with apollo.

**Comment by helfer** [comment]
Query merging doesn't actually decrease the size of your payload, it does basically what batching does, but renames everything and puts it into the same query.

Maybe you will sleep better knowing that the facebook people say that they're going to remove all dynamic query features in Relay 2? 🙂 Dynamic queries are an idea that looks great on paper, but does more harm than good in practice.
